/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists alert rules (optionally one user's).
         * @description # Errors
         *     `500` on backend failure.
         */
        get: operations["list_alert_rules"];
        put?: never;
        /**
         * Creates an alert rule.
         * @description # Errors
         *     `400` on a body outside the contracts; `500` on backend failure.
         */
        post: operations["create_alert_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alert-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replaces an alert rule.
         * @description # Errors
         *     `400` on a body outside the contracts; `404` for an unknown rule; `500`
         *     on backend failure.
         */
        put: operations["update_alert_rule"];
        post?: never;
        /**
         * Deletes an alert rule (its delivery ledger rows cascade with it).
         * @description # Errors
         *     `404` for an unknown rule; `500` on backend failure.
         */
        delete: operations["delete_alert_rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists all jurisdictions (id order) with their regimes joined in.
         * @description # Errors
         *     `500` on backend failure, in the consistent error envelope.
         */
        get: operations["list_jurisdictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/politicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists politicians in ascending ULID order, optionally name-filtered.
         * @description # Errors
         *     `400` on a malformed cursor or limit; `500` on backend failure — all in
         *     the consistent error envelope.
         */
        get: operations["list_politicians"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/politicians/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches one politician's profile: person, mandates, record summary.
         * @description # Errors
         *     `404` for an unknown politician; `500` on backend failure — all in the
         *     consistent error envelope.
         */
        get: operations["politician_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/politicians/{id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists one politician's disclosure records in ascending ULID order.
         * @description # Errors
         *     `400` on a malformed cursor or limit; `404` for an unknown politician;
         *     `500` on backend failure — all in the consistent error envelope.
         */
        get: operations["politician_records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists disclosure records in ascending ULID order.
         * @description # Errors
         *     `400` on a malformed cursor, limit or filter; `500` on backend failure —
         *     all in the consistent error envelope.
         */
        get: operations["list_records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches one record with provenance and its supersession chain.
         * @description # Errors
         *     `404` for an unknown record; `500` on backend failure — all in the
         *     consistent error envelope.
         */
        get: operations["get_record"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists all disclosure regimes — the scorecard rows — in id order.
         * @description # Errors
         *     `500` on backend failure, in the consistent error envelope.
         */
        get: operations["list_regimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists review tasks in ranking order (design §7.2 queue).
         * @description # Errors
         *     `400` on a malformed status, cursor or limit; `500` on backend failure —
         *     all in the consistent error envelope.
         */
        get: operations["list_review_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches one review task with its full adjudication surface.
         * @description # Errors
         *     `404` for an unknown task; `500` on backend failure.
         */
        get: operations["get_review_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-tasks/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The audit log of one task: every resolve attempt, in order.
         * @description # Errors
         *     `404` for an unknown task; `500` on backend failure.
         */
        get: operations["review_task_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-tasks/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolves one review task through the pipeline promote path (the single
         *     write authority; design §7.2). Every attempt that carries a verdict is
         *     audit-logged — applied, conflicting and failed alike.
         * @description # Errors
         *     `400` on a malformed body; `404` for an unknown task; `409` when the task
         *     is already resolved; `500` when the resolution fails closed (e.g. a
         *     correction violating the details contract) — the attempt is still
         *     audit-logged.
         */
        post: operations["resolve_review_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Searches politicians (name/alias) and instruments (name/ticker).
         * @description # Errors
         *     `400` on a missing or blank `q`; `500` on backend failure — all in the
         *     consistent error envelope.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One delivery channel of an alert rule (`alert_rule.channels` element). */
        AlertChannel: {
            /** @description Destination address. */
            to: string;
            /** @enum {string} */
            type: "email";
        } | {
            /** @description Per-rule shared secret for the HMAC signature. */
            secret: string;
            /** @enum {string} */
            type: "webhook";
            /** @description POST target URL. */
            url: string;
        };
        /** @description One alert rule. */
        AlertRule: {
            /** @description Inactive rules never match. */
            active: boolean;
            /** @description Delivery channels; at most one per channel type. */
            channels: components["schemas"]["AlertChannel"][];
            /**
             * Format: date-time
             * @description When the rule was created.
             */
            created_at: string;
            /**
             * @description Digest mode: matches accumulate and ship as one periodic summary
             *     instead of instant per-record sends.
             */
            digest: boolean;
            /**
             * @description Filter in the shared record grammar — identical to `/v1/records`
             *     query parameters (design §6.3: one grammar, learned once).
             */
            filter: components["schemas"]["RecordFilter"];
            /** @description Rule ULID. */
            id: string;
            /**
             * Format: date-time
             * @description When the rule was last updated.
             */
            updated_at: string;
            /** @description Owning user (free text until accounts land — goal 050). */
            user_id: string;
        };
        /** @description Create/replace body for an alert rule (`POST` and `PUT` share it). */
        AlertRuleSpec: {
            /** @description Whether the rule matches at all (defaults to active). */
            active?: boolean;
            /** @description Delivery channels; at least one, at most one per channel type. */
            channels: components["schemas"]["AlertChannel"][];
            /** @description Digest mode (defaults to instant). */
            digest?: boolean;
            /** @description Filter in the shared record grammar; unknown keys are rejected. */
            filter: components["schemas"]["RecordFilter"];
            /** @description Owning user (free text until accounts land — goal 050). */
            user_id: string;
        };
        /**
         * @description `asset_class` vocabulary (design §4.2 column comment).
         * @enum {string}
         */
        AssetClass: "equity" | "bond" | "fund" | "option" | "crypto" | "commodity" | "real_estate" | "private" | "other";
        /**
         * @description ISO 4217 currency code (`char(3)` in DDL), uppercase on the wire — `snake_case`
         *     would mangle codes. Closed set for now; extend as regimes land (visible in the
         *     schema snapshot).
         * @enum {string}
         */
        Currency: "EUR" | "GBP" | "USD";
        /**
         * @description One canonical disclosure record (Gold `disclosure_record`, design §4.2).
         *     `verification_state` is present on EVERY record — honesty travels with
         *     the data.
         */
        DisclosureRecord: {
            /**
             * Format: date
             * @description Snapshot date for holdings.
             */
            as_of_date?: string | null;
            /** @description Asset class vocabulary. */
            asset_class: components["schemas"]["AssetClass"];
            /** @description Asset description exactly as filed, always kept (invariant 2). */
            asset_description_raw: string;
            /**
             * Format: date-time
             * @description When the record row was created.
             */
            created_at: string;
            /**
             * @description Contract-typed regime payload (validated per (regime, `record_type`)
             *     JSON Schema at promotion, invariant 5).
             */
            details: Record<string, never>;
            /**
             * Format: date
             * @description Best event date: `coalesce(transaction, notified, as_of)` (generated).
             */
            event_date?: string | null;
            /** @description Parser id / model+prompt version that produced this record. */
            extracted_by: string;
            /**
             * Format: float
             * @description Extractor confidence in `[0, 1]`.
             */
            extraction_confidence?: number | null;
            /** @description Source filing this record came from. */
            filing_id: string;
            /** @description Idempotency fingerprint (audit trail). */
            fingerprint: string;
            /** @description Record ULID (time-sortable; the pagination cursor). */
            id: string;
            /** @description Resolved instrument — `null` below threshold, never guessed (invariant 3). */
            instrument_id?: string | null;
            /**
             * Format: date
             * @description Date the interest/change was notified.
             */
            notified_date?: string | null;
            owner?: null | components["schemas"]["Owner"];
            /** @description The politician the record concerns. */
            politician_id: string;
            /** @description One of the four observation types. */
            record_type: components["schemas"]["RecordType"];
            /** @description Disclosure regime the record was filed under. */
            regime_id: string;
            side?: null | components["schemas"]["Side"];
            /** @description Superseded record in a correction chain (supersede, never update). */
            supersedes_record_id?: string | null;
            /**
             * Format: date
             * @description Date the transaction happened.
             */
            transaction_date?: string | null;
            value?: null | components["schemas"]["ValueInterval"];
            /** @description Two-stage publication state (design §7.1) — on every record. */
            verification_state: components["schemas"]["VerificationState"];
        };
        /** @description The error envelope every non-2xx response carries. */
        ErrorBody: {
            /** @description The error itself. */
            error: components["schemas"]["ErrorDetail"];
        };
        /** @description Machine-readable error code plus a human-readable message. */
        ErrorDetail: {
            /**
             * @description Stable machine-readable code (e.g. `invalid_cursor`, `not_found`).
             * @example invalid_cursor
             */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
        };
        /**
         * @description Extraction-cache evidence for the task's document: which model produced
         *     the cached extraction and how (`provenance` carries the cross-check
         *     status when the live call recorded one). Latest entry for the document's
         *     sha + the record's extractor tag; absent for deterministic (non-LLM)
         *     parses.
         */
        ExtractionCacheInfo: {
            /**
             * Format: date-time
             * @description When the extraction was cached.
             */
            cached_at: string;
            /** @description Model that produced the cached extraction. */
            model_id: string;
            /**
             * @description How the entry was produced (audit surface): source, models, and
             *     `cross_checked` verdict when a second model re-extracted (design §5.3).
             */
            provenance: Record<string, never>;
        };
        /**
         * @description The LLM pre-review note (design §7.2): who/what extracted the target
         *     record, with what confidence, and the extraction-cache evidence when the
         *     LLM seam produced it. The record's Silver staging payload is NOT included
         *     yet (see the module-level silver-payload gap note).
         */
        ExtractionContext: {
            cache?: null | components["schemas"]["ExtractionCacheInfo"];
            /** @description Parser id / model+prompt version that produced the record. */
            extracted_by: string;
            /**
             * Format: float
             * @description Extractor confidence in `[0, 1]`.
             */
            extraction_confidence?: number | null;
        };
        /** @description Filing provenance: the source filing the record came from. */
        FilingProvenance: {
            /** @description Source-native filing id when the source has one. */
            external_id?: string | null;
            /**
             * Format: date
             * @description Date the filing was filed.
             */
            filed_date?: string | null;
            /** @description Filing ULID. */
            id: string;
            /**
             * Format: date-time
             * @description When the government made it public.
             */
            published_at?: string | null;
        };
        /** @description One instrument hit. */
        InstrumentHit: {
            /** @description Asset class as stored. */
            asset_class: string;
            /** @description Instrument ULID. */
            id: string;
            /** @description Instrument display name. */
            name: string;
            /** @description Exchange ticker when known. */
            ticker?: string | null;
        };
        /** @description ULID (26-char Crockford base32, time-sortable) */
        InstrumentId: string;
        /** @description One jurisdiction with its disclosure regimes — the scorecard row. */
        Jurisdiction: {
            /** @description Stable jurisdiction id (ISO 3166-1 alpha-2 lowercase by convention). */
            id: string;
            /** @description ISO 3166-1 alpha-2 where applicable. */
            iso_code?: string | null;
            /** @description `supranational` | `national` | `subnational`. */
            level: string;
            /** @description Display name. */
            name: string;
            /** @description Parent jurisdiction for subnational entries. */
            parent_id?: string | null;
            /**
             * @description Disclosure regimes of this jurisdiction, in id order — the
             *     transparency-scorecard metadata (design §7.3).
             */
            regimes: components["schemas"]["Regime"][];
        };
        /** @description One mandate (Gold `mandate`): a role held in a jurisdiction body. */
        Mandate: {
            /** @description The body, e.g. `US House`. */
            body: string;
            /** @description District code as filed, e.g. `PA11`. */
            district?: string | null;
            /**
             * Format: date
             * @description Mandate end; `null` while active.
             */
            end_date?: string | null;
            /** @description Mandate ULID. */
            id: string;
            /** @description Jurisdiction of the body (`jurisdiction.id`, e.g. `us`). */
            jurisdiction_id: string;
            /** @description Party affiliation when known. */
            party?: string | null;
            /** @description Role held, e.g. `Representative`. */
            role: string;
            /**
             * Format: date
             * @description Mandate start (roster-attested "active since at least" bound).
             */
            start_date: string;
        };
        /**
         * @description `owner` CHECK: whose asset the record concerns. `self` is a Rust keyword,
         *     hence the `Self_` variant with an explicit wire rename.
         * @enum {string}
         */
        Owner: "self" | "spouse" | "dependent" | "joint" | "unknown";
        /** @description One politician (Gold `politician`, design §4.2). */
        Politician: {
            /** @description Canonical person name (no honorific). */
            canonical_name: string;
            /** @description Politician ULID (the pagination cursor). */
            id: string;
            /** @description Wikidata QID when linked. */
            wikidata_qid?: string | null;
        };
        /** @description ULID (26-char Crockford base32, time-sortable) */
        PoliticianId: string;
        /** @description One page of politicians; the same `next_cursor` rule as `/v1/records`. */
        PoliticianPage: {
            /** @description Politicians in ascending ULID order. */
            items: components["schemas"]["Politician"][];
            /** @description Pass back as `cursor` to fetch the page after this one; `null` at the end. */
            next_cursor?: string | null;
        };
        /**
         * @description A politician profile: the person, their mandates, and a record summary
         *     (the profile page's above-the-fold data, design §6.4).
         */
        PoliticianProfile: {
            /** @description Canonical person name (no honorific). */
            canonical_name: string;
            /** @description Politician ULID. */
            id: string;
            /** @description Mandates, most recent first. */
            mandates: components["schemas"]["Mandate"][];
            /** @description Disclosure-record summary (count + event-date range). */
            records: components["schemas"]["RecordSummary"];
            /** @description Wikidata QID when linked. */
            wikidata_qid?: string | null;
        };
        /**
         * @description Full provenance of one record: filing, archived raw document, and the
         *     regime it was filed under (with its methodology metadata).
         */
        Provenance: {
            /** @description The source filing. */
            filing: components["schemas"]["FilingProvenance"];
            /** @description Our archived copy of the official document. */
            raw_document: components["schemas"]["RawDocumentProvenance"];
            /** @description The disclosure regime the record was filed under. */
            regime: components["schemas"]["Regime"];
        };
        /**
         * @description Raw-document provenance: our archived copy of the official document
         *     (invariant 2: raw is sacred — official link + archived copy, design §7.3).
         */
        RawDocumentProvenance: {
            /**
             * Format: date-time
             * @description When we fetched the document.
             */
            fetched_at: string;
            /** @description Raw document ULID. */
            id: string;
            /** @description sha256 of the archived Bronze bytes (integrity + citability). */
            sha256: string;
            /** @description Official source URL the document was fetched from. */
            source_url?: string | null;
        };
        /**
         * @description One record with its trust surface (design §7.3): provenance plus the full
         *     supersession history in both directions (invariant 1: corrections insert
         *     superseding rows, so history is a chain of records).
         */
        RecordDetail: {
            /** @description Where it came from. */
            provenance: components["schemas"]["Provenance"];
            /** @description The record itself. */
            record: components["schemas"]["DisclosureRecord"];
            /** @description Corrections that (transitively) supersede this one, ascending ULID. */
            superseded_by: components["schemas"]["DisclosureRecord"][];
            /**
             * @description Records this one (transitively) supersedes — the corrected history,
             *     ascending ULID (= insertion-time) order.
             */
            supersedes: components["schemas"]["DisclosureRecord"][];
        };
        /**
         * @description A conjunctive filter over `disclosure_record` (design §6.1 filter list:
         *     jurisdiction, type, `asset_class`, instrument, politician, date range,
         *     value bounds, `verification_state`). Every field is optional; an empty
         *     filter matches everything.
         *
         *     Value-bound semantics: a record matches when its declared band
         *     `[value_low, value_high|∞]` OVERLAPS `[value_min, value_max]`; records
         *     without a declared value never match a value bound.
         */
        RecordFilter: {
            asset_class?: null | components["schemas"]["AssetClass"];
            /**
             * Format: date
             * @description Only records with `event_date` on or after this date.
             */
            event_date_from?: string | null;
            /**
             * Format: date
             * @description Only records with `event_date` on or before this date.
             */
            event_date_to?: string | null;
            instrument_id?: null | components["schemas"]["InstrumentId"];
            /**
             * @description Only records filed under a regime of this jurisdiction
             *     (`jurisdiction.id`, e.g. `us`).
             */
            jurisdiction_id?: string | null;
            politician_id?: null | components["schemas"]["PoliticianId"];
            record_type?: null | components["schemas"]["RecordType"];
            /**
             * @description Only records whose declared value band can stay at this amount or less
             *     (decimal string — invariant 7).
             */
            value_max?: string | null;
            /**
             * @description Only records whose declared value band can reach this amount or more
             *     (decimal string — invariant 7).
             */
            value_min?: string | null;
            verification_state?: null | components["schemas"]["VerificationState"];
        };
        /**
         * @description One page of records; `next_cursor` is the last item's ULID, `null` when
         *     the listing is exhausted (design §6.1: cursor pagination on ULIDs).
         */
        RecordPage: {
            /** @description Records in ascending ULID (= insertion-time) order. */
            items: components["schemas"]["DisclosureRecord"][];
            /** @description Pass back as `cursor` to fetch the page after this one; `null` at the end. */
            next_cursor?: string | null;
        };
        /** @description Aggregate summary of a politician's disclosure records. */
        RecordSummary: {
            /**
             * Format: int64
             * @description Total records concerning the politician.
             */
            count: number;
            /**
             * Format: date
             * @description Earliest `event_date` across those records.
             */
            first_event_date?: string | null;
            /**
             * Format: date
             * @description Latest `event_date` across those records.
             */
            last_event_date?: string | null;
        };
        /**
         * @description `record_type` CHECK: the four observation types, one table (design D1).
         * @enum {string}
         */
        RecordType: "transaction" | "holding" | "interest" | "change_notification";
        /**
         * @description One disclosure regime — a jurisdiction body's disclosure rules and the
         *     transparency-scorecard metadata (design §6.1/§7.3).
         */
        Regime: {
            /** @description Disclosing body, e.g. `US House`. */
            body: string;
            /** @description Free-form filing cadence description. */
            cadence?: string | null;
            /**
             * Format: int32
             * @description Statutory maximum disclosure lag in days.
             */
            disclosure_lag_days?: number | null;
            /**
             * Format: date
             * @description Date the regime's rules took effect.
             */
            effective_from: string;
            /**
             * Format: date
             * @description Date the rules stopped applying; `null` while current.
             */
            effective_to?: string | null;
            /** @description Regime ULID (stable adapter constant). */
            id: string;
            /** @description Jurisdiction the regime belongs to (`jurisdiction.id`, e.g. `us`). */
            jurisdiction_id: string;
            /**
             * @description `transaction_report` | `periodic_declaration` | `change_notification`
             *     | `none`.
             */
            regime_type: string;
            /** @description Official source landing page. */
            source_url?: string | null;
            /**
             * @description Value precision the regime discloses: `exact` | `banded` |
             *     `categorical` | `none`.
             */
            value_precision: string;
        };
        /**
         * @description Resolve request: reviewer identity plus one verdict. `regime_code` and
         *     `corrected` travel only with `verdict = "edit"` (they select the details
         *     contract and carry the corrected facts); supplying them with any other
         *     verdict fails closed. Corrected identity fields (`filing_id`,
         *     `politician_id`, `regime_id`) may be omitted — promote pins identity from
         *     the original row and ignores reviewer-supplied values.
         */
        ResolveRequest: {
            /** @description Corrected facts for an edit, in the `GoldCandidate` wire shape. */
            corrected?: Record<string, never> | null;
            /** @description Optional note, recorded verbatim in the audit log. */
            note?: string | null;
            /** @description Details-registry arm for an edit (e.g. `us_house`). */
            regime_code?: string | null;
            /** @description Reviewer identity — free text until accounts land (goal 050). */
            reviewer: string;
            /** @description `confirm` | `reject` | `edit`. */
            verdict: string;
        };
        /**
         * @description What an applied resolution did (non-applied attempts surface as errors:
         *     `409` for an already-resolved task, `5xx` for a failed resolution).
         */
        ResolveResponse: {
            /** @description Always `applied`. */
            outcome: string;
            /** @description The adjudicated record. */
            record_id: string;
            /**
             * @description The superseding `corrected` record an edit inserted (`null` for
             *     confirm/reject).
             */
            superseding_record_id?: string | null;
        };
        /**
         * @description One resolve attempt in the audit log — exactly one row per attempt,
         *     whatever came of it.
         */
        ReviewAuditEntry: {
            /** @description Record ids the attempt touched (`[]` for non-applied attempts). */
            affected_record_ids: string[];
            /**
             * Format: date-time
             * @description When the attempt happened.
             */
            created_at: string;
            /** @description Audit row ULID (time-sortable). */
            id: string;
            /** @description Reviewer note, verbatim. */
            note?: string | null;
            /**
             * @description `applied` | `conflict` (task already resolved) | `failed` (rolled
             *     back whole).
             */
            outcome: string;
            /** @description The task the attempt adjudicated. */
            review_task_id: string;
            /** @description Who attempted (free text until goal 050 auth). */
            reviewer: string;
            /** @description `confirm` | `edit` | `reject`. */
            verdict: string;
        };
        /**
         * @description One queue entry: the task plus its target-record summary (`null` when the
         *     task targets something other than a disclosure record).
         */
        ReviewQueueItem: {
            record?: null | components["schemas"]["ReviewTargetSummary"];
            /** @description The task itself. */
            task: components["schemas"]["ReviewTask"];
        };
        /**
         * @description One page of the review queue, ranked `priority_score` desc, then
         *     `created_at` asc (oldest first within a priority), then id.
         */
        ReviewQueuePage: {
            /** @description Queue entries in ranking order. */
            items: components["schemas"]["ReviewQueueItem"][];
            /**
             * @description Pass back as `cursor` to fetch the page after this one; `null` at the
             *     end. Ranking (not id order) is preserved across pages.
             */
            next_cursor?: string | null;
        };
        /** @description Target-record summary on a queue item — the reviewer's scan surface. */
        ReviewTargetSummary: {
            /** @description Asset description exactly as filed (invariant 2). */
            asset_description_raw: string;
            /** @description Parser id / model+prompt version that produced the record. */
            extracted_by: string;
            /**
             * Format: float
             * @description Extractor confidence in `[0, 1]`.
             */
            extraction_confidence?: number | null;
            /** @description Canonical name of the politician the record concerns. */
            politician_name: string;
            /** @description The targeted `disclosure_record`. */
            record_id: string;
            /** @description One of the four observation types. */
            record_type: components["schemas"]["RecordType"];
            value?: null | components["schemas"]["ValueInterval"];
            /** @description Two-stage publication state (design §7.1). */
            verification_state: components["schemas"]["VerificationState"];
        };
        /** @description One `review_task` row (design §4.2). */
        ReviewTask: {
            /** @description Claimed reviewer, when assigned. */
            assignee?: string | null;
            /**
             * Format: date-time
             * @description When the task was opened.
             */
            created_at: string;
            /** @description Task ULID (time-sortable; the queue pagination cursor). */
            id: string;
            /**
             * Format: float
             * @description Queue rank: impact × uncertainty (design §7.2); higher reviews first.
             */
            priority_score: number;
            /** @description Why the task was opened (e.g. `ptr_amendment_unlinked`). */
            reason: string;
            /** @description Verdict payload once resolved. */
            resolution?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description When the task was resolved.
             */
            resolved_at?: string | null;
            /** @description `open` | `resolved` | `dismissed`. */
            status: string;
            /** @description Id of the targeted row. */
            target_id: string;
            /** @description What the task targets (e.g. `disclosure_record`). */
            target_kind: string;
        };
        /**
         * @description One review task with its full adjudication surface: the target record in
         *     the public trust shape (provenance + supersession history) and the
         *     extraction context.
         */
        ReviewTaskDetail: {
            extraction?: null | components["schemas"]["ExtractionContext"];
            record?: null | components["schemas"]["RecordDetail"];
            /** @description The task itself. */
            task: components["schemas"]["ReviewTask"];
        };
        /**
         * @description Typed search results: one arm per entity kind, each capped at 20 hits in
         *     id order.
         */
        SearchResults: {
            /** @description Instruments whose name or ticker contains the query. */
            instruments: components["schemas"]["InstrumentHit"][];
            /** @description Politicians whose canonical name or as-filed alias contains the query. */
            politicians: components["schemas"]["Politician"][];
            /** @description The query as evaluated (trimmed). */
            query: string;
        };
        /**
         * @description `side` CHECK: direction of a transaction.
         * @enum {string}
         */
        Side: "buy" | "sell" | "exchange";
        /**
         * @description A money interval `low ..= high` in `currency`. Exact figures are `low == high`;
         *     `high == None` is an open-ended threshold (UK "over £70,000"). Construction is
         *     the only door: `high < low` never exists — in memory or on the wire, because
         *     the manual `Deserialize` impl funnels back through [`ValueInterval::new`].
         */
        ValueInterval: {
            currency: components["schemas"]["Currency"];
            high?: string | null;
            low: string;
        };
        /**
         * @description `verification_state` CHECK: two-stage publication states (design §4.2).
         * @enum {string}
         */
        VerificationState: "unverified" | "verified" | "corrected" | "disputed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alert_rules: {
        parameters: {
            query?: {
                /** @description Only rules owned by this user. */
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All matching rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_alert_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleSpec"];
            };
        };
        responses: {
            /** @description The created rule */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Body violates the filter/channel contracts */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_alert_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleSpec"];
            };
        };
        responses: {
            /** @description The updated rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Body violates the filter/channel contracts */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown rule */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_alert_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown rule */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_jurisdictions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All jurisdictions with their disclosure regimes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jurisdiction"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_politicians: {
        parameters: {
            query?: {
                /**
                 * @description Case-insensitive substring over canonical name and as-filed aliases
                 *     (plain ILIKE; `%`/`_` are literals).
                 */
                q?: string;
                /**
                 * @description Pagination cursor: the `id` of the last politician on the previous
                 *     page (from `next_cursor`). Pages begin strictly after it.
                 */
                cursor?: string;
                /** @description Page size, `1..=200`; defaults to 50. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of politicians */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliticianPage"];
                };
            };
            /** @description Malformed cursor or limit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    politician_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Politician ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The politician's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliticianProfile"];
                };
            };
            /** @description Unknown politician */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    politician_records: {
        parameters: {
            query?: {
                /**
                 * @description Pagination cursor: the `id` of the last record on the previous page
                 *     (from `next_cursor`). Pages begin strictly after it.
                 */
                cursor?: string;
                /** @description Page size, `1..=200`; defaults to 50. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Politician ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the politician's records; every record carries verification_state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Malformed cursor or limit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown politician */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_records: {
        parameters: {
            query?: {
                /**
                 * @description Pagination cursor: the `id` of the last record on the previous page
                 *     (from `next_cursor`). Pages begin strictly after it.
                 */
                cursor?: string;
                /** @description Page size, `1..=200`; defaults to 50. */
                limit?: number;
                /**
                 * @description Only records filed under a regime of this jurisdiction
                 *     (`jurisdiction.id`, e.g. `us`).
                 */
                jurisdiction_id?: string;
                /** @description Only records of this type. */
                record_type?: components["schemas"]["RecordType"];
                /** @description Only records of this asset class. */
                asset_class?: components["schemas"]["AssetClass"];
                /** @description Only records concerning this politician. */
                politician_id?: components["schemas"]["PoliticianId"];
                /**
                 * @description Only records resolved to this instrument (below-threshold matches are
                 *     NULL and never match — invariant 3).
                 */
                instrument_id?: components["schemas"]["InstrumentId"];
                /** @description Only records with `event_date` on or after this date. */
                event_date_from?: string;
                /** @description Only records with `event_date` on or before this date. */
                event_date_to?: string;
                /**
                 * @description Only records whose declared value band can reach this amount or more
                 *     (decimal string — invariant 7).
                 */
                value_min?: string;
                /**
                 * @description Only records whose declared value band can stay at this amount or less
                 *     (decimal string — invariant 7).
                 */
                value_max?: string;
                /** @description Only records in this verification state. */
                verification_state?: components["schemas"]["VerificationState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of disclosure records; every record carries verification_state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Malformed cursor, limit or filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Record ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The record with provenance and supersession history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDetail"];
                };
            };
            /** @description Unknown record */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_regimes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All disclosure regimes with scorecard metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Regime"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_review_tasks: {
        parameters: {
            query?: {
                /** @description Task status filter: `open` (default) | `resolved` | `dismissed`. */
                status?: string;
                /** @description Pagination cursor: the task id of the last item on the previous page. */
                cursor?: string;
                /** @description Page size, `1..=200`; defaults to 50. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the review queue, ranked priority desc then age */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueuePage"];
                };
            };
            /** @description Malformed status, cursor or limit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_review_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review task ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task with its target record and extraction context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskDetail"];
                };
            };
            /** @description Unknown task */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    review_task_audit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review task ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All resolve attempts, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewAuditEntry"][];
                };
            };
            /** @description Unknown task */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    resolve_review_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review task ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description The verdict was applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Malformed reviewer, verdict or corrected payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown task */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The task is already resolved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The resolution failed closed and rolled back whole */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description Query text: case-insensitive substring, at least one non-blank
                 *     character; `%`/`_` are literals.
                 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Typed search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Missing or blank query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
